runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
  secure: always
  application_readable: true

- url: /js
  static_dir: js
  secure: always
  application_readable: true

- url: /static
  static_dir: static
  secure: always
  application_readable: true

- url: /application_only
  static_dir: application_only
  secure: always
  application_readable: true

- url: /alpha
  script: main.app

- url: /.*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?Icon\r
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.pyc$
- ^admin$